# Generated by Django 4.1.7 on 2023-05-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('qtdprod', models.IntegerField(max_length=255, verbose_name='Quantidade de Produtos')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Preço')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
            ],
        ),
    ]
