# Generated by Django 4.1.7 on 2023-05-17 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_produtos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='produto',
            new_name='produtos',
        ),
        migrations.AlterModelTable(
            name='produtos',
            table='produtos',
        ),
    ]
