# Generated by Django 4.2.2 on 2023-06-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_produtos", "0002_rename_produto_produtos_alter_produtos_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produtos",
            name="qtdprod",
            field=models.IntegerField(verbose_name="Quantidade de Produtos"),
        ),
    ]
