# Generated by Django 4.1.7 on 2023-05-17 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtvenda', models.DateField(max_length=8)),
                ('id_cliente', models.IntegerField(verbose_name='Quantidade de Produtos')),
                ('id_prod', models.IntegerField(verbose_name='Preço')),
                ('id_func', models.IntegerField(verbose_name='Descrição')),
            ],
            options={
                'db_table': 'vendas',
            },
        ),
    ]
