# Generated by Django 4.1.7 on 2023-05-17 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Cliente')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF do Cliente')),
                ('rg', models.CharField(max_length=11, verbose_name='RG do Cliente')),
                ('endereco', models.CharField(max_length=50, verbose_name='Endereço do Cliente')),
                ('dtnasce', models.DateField(max_length=8, verbose_name='Data de Nascimento do Cliente')),
                ('contato', models.CharField(max_length=15, verbose_name='Contato do Cliente')),
            ],
            options={
                'db_table': 'clientes',
            },
        ),
    ]
