# Generated by Django 4.1.7 on 2023-05-17 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='funcionarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Funcionário')),
                ('contato', models.CharField(max_length=15, verbose_name='Numnero de Telefone')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF do Funcionário')),
                ('rg', models.CharField(max_length=11, verbose_name='RG do Funcionário')),
                ('cidade', models.CharField(max_length=50, verbose_name='Cidade')),
                ('rua', models.CharField(max_length=50, verbose_name='Rua')),
                ('bairro', models.CharField(max_length=50, verbose_name='Bairro')),
                ('numero_casa', models.IntegerField(max_length=10, verbose_name='Número da casa')),
                ('dtnasc_func', models.DateField(max_length=8, verbose_name='Data de Nascimento do Funcionário')),
            ],
            options={
                'db_table': 'funcionarios',
            },
        ),
    ]
