# Generated by Django 4.1.7 on 2023-05-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionarios',
            name='contato',
            field=models.CharField(max_length=15, verbose_name='Número de Telefone'),
        ),
    ]
