# Generated by Django 4.2.2 on 2023-06-14 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_funcionarios", "0002_alter_funcionarios_contato"),
    ]

    operations = [
        migrations.AddField(
            model_name="funcionarios",
            name="estadocivil",
            field=models.CharField(
                default="", max_length=8, verbose_name="Estado civil"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="funcionarios",
            name="setor",
            field=models.CharField(default="", max_length=10, verbose_name="Setor"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="funcionarios",
            name="sexo",
            field=models.CharField(
                default="Masculino", max_length=9, verbose_name="Sexo do funcionário"
            ),
            preserve_default=False,
        ),
    ]
