# Generated by Django 4.2.2 on 2023-06-14 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_funcionarios", "0004_funcionarios_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="funcionarios",
            name="estadocivil",
            field=models.CharField(max_length=15, verbose_name="Estado civil"),
        ),
    ]
