# Generated by Django 4.2.2 on 2023-06-14 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_funcionarios", "0005_alter_funcionarios_estadocivil"),
    ]

    operations = [
        migrations.AddField(
            model_name="funcionarios",
            name="observacao",
            field=models.TextField(
                default="Nenhuma", max_length=500, verbose_name="Observação"
            ),
            preserve_default=False,
        ),
    ]
