# Generated by Django 4.2.2 on 2023-06-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_funcionarios", "0006_funcionarios_observacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="funcionarios",
            name="numero_casa",
            field=models.IntegerField(verbose_name="Número da casa"),
        ),
    ]
