# Generated by Django 4.2.2 on 2023-06-16 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_funcionarios", "0007_alter_funcionarios_numero_casa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="funcionarios",
            name="dtnasc_func",
            field=models.CharField(
                max_length=10, verbose_name="Data de Nascimento do Funcionário"
            ),
        ),
    ]
