# Generated by Django 4.2.2 on 2023-06-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_funcionarios", "0008_alter_funcionarios_dtnasc_func"),
    ]

    operations = [
        migrations.AlterField(
            model_name="funcionarios",
            name="setor",
            field=models.CharField(max_length=16, verbose_name="Setor"),
        ),
    ]
