# Generated by Django 4.2.2 on 2023-06-19 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_funcionarios", "0009_alter_funcionarios_setor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="funcionarios",
            name="email",
            field=models.EmailField(max_length=100, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="funcionarios",
            name="observacao",
            field=models.TextField(verbose_name="Observação"),
        ),
    ]
