# Generated by Django 4.2.2 on 2023-06-25 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_funcionarios", "0010_alter_funcionarios_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="funcionarios",
            name="estado",
            field=models.CharField(
                default="Ceará", max_length=50, verbose_name="Estado de Origem"
            ),
            preserve_default=False,
        ),
    ]
